void main() {
  Future.error(Exception());
}
